# Generated by Django 4.1 on 2022-08-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPelis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='anos',
            field=models.CharField(choices=[(2000, 2000), (2001, 2001)], default=2000, max_length=4, verbose_name='Seleccionar año'),
        ),
    ]
