# Generated by Django 4.1 on 2022-09-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPelis', '0003_pelicula_genero_alter_pelicula_anos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='pais',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(null=True),
        ),
    ]
