# Generated by Django 4.1 on 2022-09-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPelis', '0004_pelicula_director_pelicula_pais_pelicula_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='image',
            field=models.ImageField(null=True, upload_to='pelis-image'),
        ),
    ]
