# Generated by Django 4.1 on 2022-09-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPelis', '0005_pelicula_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='image',
            field=models.ImageField(null=True, upload_to='pelis-image', verbose_name='Elija una imagen'),
        ),
    ]
